// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type PostFilesMetadataRequest struct {
	// Tenant Id
	DataPartitionID string                  `header:"style=simple,explode=false,name=data-partition-id"`
	FileMetadata    components.FileMetadata `request:"mediaType=application/json"`
}

func (o *PostFilesMetadataRequest) GetDataPartitionID() string {
	if o == nil {
		return ""
	}
	return o.DataPartitionID
}

func (o *PostFilesMetadataRequest) GetFileMetadata() components.FileMetadata {
	if o == nil {
		return components.FileMetadata{}
	}
	return o.FileMetadata
}

type PostFilesMetadataResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (o *PostFilesMetadataResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostFilesMetadataResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}
