// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Ancestry - A named list of entities in the data lake as a dictionary item.
type Ancestry struct {
	// An array of one or more entity references in the data lake.
	Parents []string `json:"parents,omitempty"`
}

func (o *Ancestry) GetParents() []string {
	if o == nil {
		return nil
	}
	return o.Parents
}
