// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DatasetProperties - Dataset Properties
type DatasetProperties struct {
	// File Source Info
	FileSourceInfo FileSourceInfo `json:"FileSourceInfo"`
}

func (o *DatasetProperties) GetFileSourceInfo() FileSourceInfo {
	if o == nil {
		return FileSourceInfo{}
	}
	return o.FileSourceInfo
}
