// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FileSourceInfo - File Source Info
type FileSourceInfo struct {
	// Relative file path for the data in the file
	FileSource string `json:"FileSource"`
	// File system path to the data file as it existed before loading to the data platform
	PreloadFilePath *string `json:"PreloadFilePath,omitempty"`
	// Optional user name or reference, who created the file prior to up-loading to the platform.
	PreloadFileCreateUser *string `json:"PreloadFileCreateUser,omitempty"`
	// Optional create date and time of the file prior to uploading to the platform.
	PreloadFileCreateDate *string `json:"PreloadFileCreateDate,omitempty"`
	// Optional user name or reference, who last modified the file prior to up-loading to the platform.
	PreloadFileModifyUser *string `json:"PreloadFileModifyUser,omitempty"`
	// Optional last modified date and time of the file prior to up-loading to the platform.
	PreloadFileModifyDate *string `json:"PreloadFileModifyDate,omitempty"`
	// user-friendly file name.
	Name *string `json:"Name,omitempty"`
	// Length of file in bytes. Implemented as string. The value must be convertible to a long integer (sizes can become very large).
	FileSize *string `json:"FileSize,omitempty"`
	// Encoding Format Type ID
	EncodingFormatTypeID *string `json:"EncodingFormatTypeID,omitempty"`
	// MD5 checksum of file bytes - a 32 byte hexadecimal number
	Checksum *string `json:"Checksum,omitempty"`
	// The name of the checksum algorithm e.g. MD5, SHA-256.
	ChecksumAlgorithm *string `json:"ChecksumAlgorithm,omitempty"`
}

func (o *FileSourceInfo) GetFileSource() string {
	if o == nil {
		return ""
	}
	return o.FileSource
}

func (o *FileSourceInfo) GetPreloadFilePath() *string {
	if o == nil {
		return nil
	}
	return o.PreloadFilePath
}

func (o *FileSourceInfo) GetPreloadFileCreateUser() *string {
	if o == nil {
		return nil
	}
	return o.PreloadFileCreateUser
}

func (o *FileSourceInfo) GetPreloadFileCreateDate() *string {
	if o == nil {
		return nil
	}
	return o.PreloadFileCreateDate
}

func (o *FileSourceInfo) GetPreloadFileModifyUser() *string {
	if o == nil {
		return nil
	}
	return o.PreloadFileModifyUser
}

func (o *FileSourceInfo) GetPreloadFileModifyDate() *string {
	if o == nil {
		return nil
	}
	return o.PreloadFileModifyDate
}

func (o *FileSourceInfo) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *FileSourceInfo) GetFileSize() *string {
	if o == nil {
		return nil
	}
	return o.FileSize
}

func (o *FileSourceInfo) GetEncodingFormatTypeID() *string {
	if o == nil {
		return nil
	}
	return o.EncodingFormatTypeID
}

func (o *FileSourceInfo) GetChecksum() *string {
	if o == nil {
		return nil
	}
	return o.Checksum
}

func (o *FileSourceInfo) GetChecksumAlgorithm() *string {
	if o == nil {
		return nil
	}
	return o.ChecksumAlgorithm
}
