// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FileMetadataResponse - File metadata Response
type FileMetadataResponse struct {
	// Unique identifier generated by the system for the file metadata record.
	ID *string
}

func (o *FileMetadataResponse) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}
